server {
    listen 80;
    server_name site.elegso.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
        return 410;
    }
}

server {
    listen 80;
    server_name elegso.ru www.elegso.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
