server {
    listen 80;
    server_name 1cbo.elegso.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://1cbo.elegso.ru$request_uri;
    }
}

server {
    listen 80;
    server_name elegso.ru www.elegso.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://elegso.ru$request_uri;
    }
}
